Create ws-server.js
Interoperability is all over the place. 

For WebSocket clients

- Chromium 138 Developer Build (Linux)

{ conn: { [Symbol(kHandle)]: {} } }
{ opcode: 8 }
Close opcode.
TypeError: Parameter 1 is required in 'respond'.
    at $ (polyfills.js:28:14849)
    at respond (polyfills.js:28:21853)
    at pull (core.js{ conn: { [Symbol(kHandle)]: {} } }
{ opcode: 8 }
Close opcode.
WebSocket client connection closed
Error: EPIPE: broken pipe
:1:11961)


- Firefox Nightly 140.0a1 (2025-05-07) (64-bit)

Works with 127.0.0.1:8080

Does not work with 0.0.0.0:8080

- Bun 1.2.13

Works with builtin or Undici. Always causes broken pipe in tjs.

{ conn: { [Symbol(kHandle)]: {} } }
{ opcode: 8 }
Close opcode.
WebSocket client connection closed
Error: EPIPE: broken pipe

- Deno 2.3.1+d372c0d (canary, release, x86_64-unknown-linux-gnu)

Does nothing. Using builtin or Undici. 0.0.0.0, 127.0.0.1, or localhost.

- Node.js v24.0.0-nightly202505066102159fa1

Does nothing. Using builtin or Undici. 0.0.0.0, 127.0.0.1, or localhost.

For WebSocketStream clients

- Chromium 138 Developer Build (Linux)

Works.

writer.close() does not cause broken pipe. A different error. 
Server does not exit. 

TypeError: Parameter 1 is required in 'respond'.
    at $ (polyfills.js:28:14849)
    at respond (polyfills.js:28:21853)
    at pull (core.js:1:11961)

- Deno 

Does nothing. Using builtin or Undici. 0.0.0.0, 127.0.0.1, or localhost.

- Node.js 

Does nothing. Using builtin or Undici. 0.0.0.0, 127.0.0.1, or localhost.