docs: fixed DirHandle declaration TypeScript error with 'for await ... of'
When using the docs TypeScript declaration file, the example async iterator
code...

    const dirIter = await tjs.readdir('.');
    for await (const item of dirIter) {
        console.log(item.name);
    }

...does not compile due to a TypeScript error.

    error TS2504: Type 'DirHandle' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.

The DirHandle must be declared as an AsyncIterableIterator, which the
implementation already satisfies, instead of an AsyncIterator.

The MDN reference on `for await ... of` hints at the need for this:

    Note: for await...of doesn't work with async iterators that are not async iterables.